weatherCenterRedis-dev:
    image: npersia/redis-dev

weatherCenterNodeRed-dev:
    image: npersia/nodered-dev
    ports:
        - "8001:1880"
    links:
        - "weatherCenterRedis-dev:redisweathercenter"
    volumes:
        - "./myfiles/weatherCenter/nodeRed/data:/data"

mainAppServer-dev:
    image: npersia/bottle-dev
    ports:
        - "8000:8000"
    links:
        - "weatherCenterNodeRed-dev:noderedweathercenter"
    volumes:
        - "./myfiles/mainAppServer:/myfiles"



subteCenterNodeRed-dev:
    image: npersia/nodered-dev
    ports:
        - "8002:1880"
    volumes:
        - "./myfiles/subteCenter/nodeRed/data:/data"
