NAME_MAIN_APPSERVER="mainAppServer"
FILES_MAIN_APPSERVER=$(pwd)"/../myfiles/mainAppServer"
PORT_MAIN_APPSERVER=8000
ENV_MAIN_APPSERVER="dev"
IMAGE_MAIN_APPSERVER="npersia/bottle-dev"

NAME_WEATHERCENTER_REDIS="weatherCenterRedis"
ENV_WEATHERCENTER_REDIS="dev"
IMAGE_WEATHERCENTER_REDIS="npersia/redis-dev"

NAME_WEATHERCENTER_NODERED="weatherCenterNodeRed"
FILES_WEATHERCENTER_NODERED=$(pwd)"/../myfiles/weatherCenter/nodeRed/data"
PORT_WEATHERCENTER_NODERED=8001
ENV_WEATHERCENTER_NODERED="dev"
IMAGE_WEATHERCENTER_NODERED="npersia/nodered-dev"
LINK_REDIS_WEATHERCENTER_NODERED=$NAME_WEATHERCENTER_REDIS-$ENV_WEATHERCENTER_REDIS 


